### ISSUE TITLE
TypeError: long_call_spread() missing 2 required positional arguments: 'end' and 'filters'

### ISSUE THREAD

**Issue by Friedrichz** [michaelchu/optopsy#24]
Hey, 

when running the sample code as is with the dataset you provided I get this error
>  File "strategies/sample_strat.py", line 27, in run_strategy
>   return op.option_strategies.long_call_spread(data, filters)
>TypeError: long_call_spread() missing 2 required positional arguments: 'end' and 'filters'

Any idea what went wrong? I don´t see where long_call_spread() takes end as argument..
Thank you!

**Comment by michaelchu** [comment]
Hi, 

I'll need more info to be able to help you. Can you show me the file you are running with and the data you are running against?
