### ISSUE TITLE
long_call() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by erv4gen** [michaelchu/optopsy#33]
Hi Michael,
I was working with version #23 of your package. After the update to #32 I start receiving the following error when running the strategy: 

> TypeError: long_call() takes 1 positional argument but 2 were given

According to your example from 'strategies/sample_spx_strategy.py' next code is using from api call to optopsy module:
`spreads = op.long_call(data, filters)`

I chected out optopsy/option_strategies.py and it seems to secive only one argument:
```
def long_call(leg):
    return _create_strategy([leg], singles_checks, [(OptionType.CALL, 1)])
```
Is there any changes in API that wasn't reflected in the example file 'strategies/sample_spx_strategy.py'  or I'm doing something wrong?

Thanks!

**Comment by michaelchu** [comment]
Hi, I recommend sticking with the previous official release version  1.0.3 (before #32) as I am working on some heavy API changes which will take some time to complete.

I plan to release it under version 2 in the future.

 Sorry for the inconveniences.

**Comment by erv4gen** [comment]
Ok, I think I missed it at some point, thx!
