### ISSUE TITLE
running strategies/sample_spx_strategy.py sample failed issue

### ISSUE THREAD

**Issue by soulshell** [michaelchu/optopsy#35]
Hi Michael 

after clone the code and run the test sample_spx_strategy.py failed, said that DO not get /data/SPX_2014_2018.pk file, where can we download the file 

And I notice in the csv file, we've calculated the delta/gamma so on, but the downloaded data does't include that value, does it means we have to cal them from the org csv file to a new one like data.csv or data_full.csv ?

thanks

**Comment by michaelchu** [comment]
Hi Soushell,

SPX_2014_2018.pkl is a file I created with some historical data I've purchased. 

You should download your own dataset from sites such as the following:

https://datashop.cboe.com/

or 

https://www.historicaloptiondata.com/

Make sure you download data that includes the greeks and compile it into a Pandas dataframe with the required columns as mentioned in the sample_spx_strategy.py file

**Comment by soulshell** [comment]
THX

> Hi Soushell,
> 
> SPX_2014_2018.pkl is a file I created with some historical data I've purchased.
> 
> You should download your own dataset from sites such as the following:
> 
> https://datashop.cboe.com/
> 
> or
> 
> https://www.historicaloptiondata.com/
> 
> Make sure you download data that includes the greeks and compile it into a Pandas dataframe with the required columns as mentioned in the sample_spx_strategy.py file

THX
