### ISSUE TITLE
argument issue in sample_spx_strategy.py issue

### ISSUE THREAD

**Issue by soulshell** [michaelchu/optopsy#36]
Hi Michael

Another issue I'm quite curious how to run the final strategies, It's ok to run all test in tests/integration, but when running the strategies/, for example sample_spx_strategy.py. I've downloaded the data and format them well

But the long_call can NOT run well, short call neither, said that 

Traceback (most recent call last):
  File "sample_spx_strategy.py", line 62, in <module>
    run_strategy()
  File "sample_spx_strategy.py", line 57, in run_strategy
    spreads = op.long_call(data, filters)
TypeError: long_call() takes 1 positional argument but 2 were given

Have checked all in option_strategies.py all have no dataframe as input, but actually we need it 

So this part need a update ?

**Comment by michaelchu** [comment]
Hi SoulShell,

The sample code on master is a bit outdated unfortunately, as I haven't had much time to fix it. If you look at the test, you can see that I am using the functions in a different way. You can try to write a simple strategy following the samples in the test instead.

I am in the middle of a refactor and I would advise you to wait until I update the code as it may still have changes.

Thanks for your understanding.
