### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by cooldharma** [michaelchu/optopsy#40]
Hello Michael

Thanks for creating this project.  This one comes nearest to my backtesting requirements (mainly want to backtest straddles & strangles), but I wonder if this project is still active and any plans of the release 2.0 that you mentioned here?

Best Regards
Dharma

**Comment by michaelchu** [comment]
Hi Dharma, 

Thanks for your interest in this library, unfortunately I am currently no working on this project as I have less time to devout to it. However, it is not difficult to simulate straddles and strangles individually without this library, I can send you some sample code in SQL which you can easily translate into to Python or use as is.

Let me know if you are interested.

**Comment by bryanbmb** [comment]
Hi Michael,

Similarly to Dharma, I am primarily interested in back testing strangles. Can you please elaborate on how to back test strangles?

Regards,
Bryan

**Comment by dikshita84** [comment]
Hello Michael, 

i am struggling to backtest strangles and couldnt find any valid content. i think optopsy can help me out but it's not working. i know u must be busy with ur work but can you help me out with it.i'll be really greatful to u.

regards,
Dikshita.

**Comment by michaelchu** [comment]
hi @bryanbmb @dikshita84 , my time has freed, and I am working on an update to optopsy that will allow you to backtest strangles/straddles. Please stay tuned for V2.

**Comment by michaelchu** [comment]
hi @bryanbmb @dikshita84 @cooldharma I have release v2.0.0b2, which add support for straddles and strangles. Please give that version a try and let me know if you encounter any issues.

**Comment by dikshita84** [comment]
Thanks for the update.
i'll definitely try on straddles and strangles.
