### ISSUE TITLE
Planned work as mentioned in the README

### ISSUE THREAD

**Issue by jjphung** [michaelchu/optopsy#59]
Fantastic repo and currently the only repo that backtests stock derivatives.

Just a quick question, do you have any plans to work on the 3rd bullet point in the README under "Use cases for Optopsy": Run backtests on option strategies based on entry conditions generated from Optopsy (Planned)?

If not, what did you have in mind for that bullet point? I would imagine it includes being able to generate graphs and charts similar to that of other backtesting libraries to measure things like Annual return, sharpe and sortino ratio, max drawdown, etc.

**Comment by michaelchu** [comment]
hi @jjphung, thanks for trying my library!

As for your question, that bullet point refers to a previous discussion I had [here](https://github.com/michaelchu/optopsy/issues/51); 

In short, I was planning to implement a functionality where the library can take in a list of entry and exit dates and have the backtest these dates. These dates should be generated via indicators as plugins - which I had also planned to implement.

At the moment I don't have much time to devote to this feature. However, you can subscribe to the project and be updated when I decide to implement it.
