### ISSUE TITLE
SPX singles examples generates empty output

### ISSUE THREAD

**Issue by monological** [michaelchu/optopsy#61]
I updated the script to point to './data/sample_spx_data.csv' since './data/Sample_SPX_20151001_to_20151030.csv'  doesn't exist.

Then I ran it and it gave me the following empty output.

```
python3 spx_singles_example.py

Statistics for SPX long calls from 2015-10-01 to 2015-10-30

| index   | count   | mean   | std   | min   | 25%   | 50%   | 75%   | max   |
|---------|---------|--------|-------|-------|-------|-------|-------|-------|
Program Executed in 0.0
```

**Comment by michaelchu** [comment]
Hi, sorry for the late reply, are you still having this problem?

**Comment by hoangnm** [comment]
Same for me. It shows the empty output.

**Comment by mvnchi** [comment]
I am running into the same problem with that the example data provided ( './data/sample_spx_data.csv' ) aswell as own data which has the following structure. 

<html><body>

underlying_symbol | underlying_price | option_type | expiration | quote_date | strike | bid | ask | delta
-- | -- | -- | -- | -- | -- | -- | -- | --


</body>
</html>

Either way it is returning an empty table. Can you confirm that the library is still working?
